### ISSUE TITLE
windows binaries of unclear origin

### ISSUE THREAD

**Issue by mariolenz** [ispim/inspur.ispim#35]
Hi there!

It looks like you're shipping some weird files in this collection via galaxy: ansible-community/ansible-build-data#426

I **strongly** suggest to do another (bugfix) release ASAP without those files, ideally without the whole `venv` folder because I don't see how it could be necessary for the collection to work.

Thanks in advance
Mario

**Comment by felixfontein** [comment]
@ISIB-Group @baoshanwang @ieisystem please create a new patch release without these files and preferably no other changes (except version + changelog entry) ASAP (preferably still this week) so we can release Ansible 10.0.1 and Ansible 9.6.1 without these files. Thanks!

**Comment by felixfontein** [comment]
We will create new releases 10.0.1 and 9.6.1 tomorrow morning (starting at 05:00 UTC) that will either include updated versions of the collections, or pin inspur.ispim to 2.2.0 (instead of 2.2.1) and will remove kaytus.ksmanage completely (2.2.1 was the first version added to Ansible). We will then yank 9.6.0 and 10.0.0.

This means that if you didn't create a new release before 05:00 UTC, inspur.ispim will be (temporarily) pinned to 2.2.0 in Ansible 9 and 10.

**Comment by felixfontein** [comment]
I forgot to ping @ispim in the above.

**Comment by felixfontein** [comment]
Thanks a lot or creating the new release! It's now included in 9.6.1 and 10.0.1 that were just released.

(Can someone please close this? I don't have the appropriate rights since I didn't open it :) )

**Comment by mariolenz** [comment]
Thanks a lot or creating the new release!
